app/mods/bookmark/models.py
# app/mods/bookmark/models.py

from datetime import datetime

from app import db
from app.models import Tag



bookmarksTags = db.Table('bookmarks_tags',
    db.Column('bookmarkId', db.Integer, db.ForeignKey('bookmarks.id')),
    db.Column('tagId', db.Integer, db.ForeignKey('tags.id'))
)

class Bookmark(db.Model):
    __tablename__ = 'bookmarks'

    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String())
    title = db.Column(db.String())
    note = db.Column(db.String())
    visitCount = db.Column(db.Integer(), default=0)
    lastVisitStamp = db.Column(db.DateTime())
    
    tags = db.relationship('Tag', 
        order_by=Tag.name,
        secondary=bookmarksTags)

    # ------------------------------------

    @classmethod
    def Get(cls, id):
        return Bookmark.query.get(id)
    
    @classmethod
    def Delete(cls, bm):
        db.session.delete(bm)
        db.session.commit()
    
    @classmethod
    def Select(cls, **kwargs):
        # What are we querying?
        if 'tag' in kwargs:
            # Use ilike() for case-insensitive search
            criterion = Bookmark.tags.any(Tag.name.ilike(kwargs['tag']))
            result = Bookmark.query.filter(criterion)
        elif 'popular' in kwargs:
            result = db.session.query(Bookmark)\
                .order_by(Bookmark.visitCount.desc(), Bookmark.title)
        else:
            result = db.session.query(Bookmark)
            
        # Limit?
        if 'limit' in kwargs:
            result = result.limit(kwargs['limit'])
        
        if result:
            bmList = result.all()
        else:
            bmList = []
            
        return bmList
            
        
    @classmethod
    def FindAllTags(cls):
        """ Return a list of used tags """
        tagList = db.session.query(Tag).outerjoin(bookmarksTags)\
            .filter(bookmarksTags.c.bookmarkId != None)\
            .order_by(Tag.name.desc())\
            .all()
        
        return tagList
    
    

    """
    
    # The following may be useful one day
        
    @classmethod
    def GetAllCounts(cls):
        " Return a dict of all tags and their use counts ""
        result = db.session.query(Tag, func.count(bookmarksTags.c.bookmarkId))\
            .join(bookmarksTags)\
            .group_by(Tag)\
            .order_by(Tag.name)
        # Convert Tag objs to names
        nameList = [ (rec[0].name, rec[1]) for rec in result ]
        # Convert to dict with name => count
        nameDict = dict(nameList)
        
        return nameDict

    """
    
    # -----------------------------------------------------
        
        
    def __init__(self, url, title, **kwargs):
        super(Bookmark, self).__init__(**kwargs);
        self.url = url
        self.title = title
        
        
    def __repr__(self):
        return '<Bookmark ({}) ({})>'.format(self.id, self.title)


    def bumpVisitCount(self):
        self.visitCount += 1
        self.lastVisitStamp = datetime.now()
        db.session.commit()
        
        return self.visitCount

    
    """
    def _jsonify(self):
        b = self.__dict__
        del b['id']
        del b['_sa_instance_state']
        b['lastVisitStamp'] = util.formatStamp( b['lastVisitStamp'] )  # hack?

        return b
    """

app/mods/bookmark/forms.py
# app/mods/bookmark/forms.py

from wtforms import Field, Form, StringField
from wtforms.validators import DataRequired, Length, URL
#from wtforms.widgets import TextInput

from ...forms import TagListField



class BookmarkForm(Form):
    title = StringField('Title', [Length(max=255), DataRequired()])
    url = StringField('URL', [URL(), DataRequired()])
    note = StringField('Note', [Length(max=255)])
    tags = TagListField('Tags')

app/mods/bookmark/__init__.py
# app/mods/bookmark/__init__.py

from flask import Blueprint

mod = Blueprint('bookmark', __name__, template_folder='templates', static_folder='static')

from . import jinja, models, views

app/mods/bookmark/views.py
# app/mods/bookmark/views.py

from flask import flash, redirect, render_template, request, url_for
from sqlalchemy import or_

from app import db
from . import mod
from .forms import BookmarkForm
from .models import Bookmark



@mod.route('/')
def index():
    bmList = Bookmark.query.order_by( Bookmark.title ).all()
    
    return render_template('bookmark/list.html', bookmarks=bmList)


@mod.route('/search/', methods=['GET', 'POST'])
def search():
    if request.method == 'GET':
        qstr = request.args.get('q', default='')
    else:
        qstr = request.args['q']
    
    # Build/execute the query
    if qstr:
        qstr = '%' + qstr + '%'
        criterion = or_(
            Bookmark.url.ilike(qstr), 
            Bookmark.title.ilike(qstr), 
            Bookmark.note.ilike(qstr)
        )
        bmList = Bookmark.query.filter(criterion).all()
    else:
        bmList = Bookmark.query.all()
    
    return render_template('bookmark/list.html', bookmarks=bmList)


@mod.route('/popular/')
def popular():
    bmList = Bookmark.Select(popular=True, limit=20)
    
    return render_template('bookmark/list.html', bookmarks=bmList)


@mod.route('/tag/<name>/')
def tag(name):
    bmList = Bookmark.Select(tag=name)
    
    return render_template('bookmark/list.html', bookmarks=bmList)


@mod.route('/visit/<id>/')
def visit(id):
    bm = Bookmark.query.get_or_404(id)
    newCount = bm.bumpVisitCount()

    return redirect(bm.url)


@mod.route('/add/', methods=['GET', 'POST'])
def add():
    if request.method == 'GET':
        form = BookmarkForm(request.args)
    else:  # POST
        form = BookmarkForm(request.form)
        if form.validate():
            bm = Bookmark('', '')
            form.populate_obj(bm)
            db.session.add(bm)
            db.session.commit()
            flash('Bookmark added', 'success')
            return redirect( url_for('bookmark.index') )
        else:
            flash('Form validation error', 'error')

    return render_template('bookmark/add.html', form=form)


@mod.route('/edit/<id>/', methods=['GET', 'POST'])
def edit(id):
    bm = Bookmark.query.get_or_404(id)
    if request.method == 'GET':
        form = BookmarkForm(None, bm)
    else:  # POST
        form = BookmarkForm(request.form, bm)
        if form.validate():
            form.populate_obj(bm)
            db.session.commit()
            flash('Bookmark saved', 'success')
            return redirect( url_for('bookmark.index') )
        else:
            flash('Form validation error', 'error')
    
    return render_template('bookmark/edit.html', form=form, bookmarkId=id)


@mod.route('/delete/<id>/')
def delete(id):
    bm = Bookmark.query.get_or_404(id)
    Bookmark.Delete(bm)
    flash('Bookmark deleted', 'success')
    
    return redirect( url_for('bookmark.index') )

app/mods/bookmark/templates/bookmark/_form.html
{% if form.errors %}
    <ul class="errors">
        {% for field_name, field_errors in form.errors|dictsort if field_errors %}
            {% for error in field_errors %}
                <li>{{ form[field_name].label }}: {{ error }}</li>
            {% endfor %}
        {% endfor %}
    </ul>
{% endif %}

{% if bookmarkId is defined %}
    {% set actionUrl = url_for('bookmark.edit', id=bookmarkId) %}
{% else %}
    {% set actionUrl = url_for('bookmark.add') %}
{% endif %}

<form action="{{ actionUrl }}" method="post">

    <div class="field">
        <label class="label" for="title">{{ form.title.label }}</label>
        <div class="control">
            {{ form.title(class="input") }}
        </div>  
    </div>

    <div class="field">
        <label class="label" for="url">{{ form.url.label }}</label>
        <div class="control">
            {{ form.url(class="input") }}
        </div>  
    </div>
    
    <div class="field">
        <label class="label" for="note">{{ form.note.label }}</label>
        <div class="control">
            {{ form.note(class="input") }}
        </div>  
    </div>
    
    <div class="field">
        <label class="label" for="tags">{{ form.tags.label }}</label>
        <div class="control">
            {{ form.tags(class="jbr-tag-field") }}
        </div>  
    </div>
    
    <div class="field is-grouped">
        <div class="control">
            <button class="button is-link" type="submit">Save</button>
        </div>
        <div class="control">
            <a class="button is-light" href="{{ url_for('bookmark.index') }}">Cancel</a>
        </div>
    </div>
    
</form>

app/mods/bookmark/templates/bookmark/_sidebar.html
<div id="sidebar">
    <h2>Tags</h2>
    {% set tagList = findAllTags() %}
    {% set urlPat = url_for('bookmark.tag', name='zzz') %}
    <div class="jbr-tag-cloud" data-cloud-values="{{ tagList|tagListToStr }}" data-cloud-url-pat="{{ urlPat|replace('zzz', '{tag}') }}"></div>
</div>

app/mods/bookmark/templates/bookmark/add.html
{% extends 'app/layout.html' %}
{% block title %}Add Bookmark{% endblock %}

{% block body %}
    <h1>{{ self.title() }}</h1>
    {% include 'bookmark/_form.html' %}
{% endblock %}

app/mods/bookmark/templates/bookmark/edit.html
{% extends 'app/layout.html' %}
{% block title %}Edit Bookmark{% endblock %}

{% block body %}
    <h1>{{ self.title() }}</h1>
    {% include 'bookmark/_form.html' %}
{% endblock %}

app/mods/bookmark/templates/bookmark/list.html
{% extends 'app/layout.html' %}

{% from 'app/macros/modal.html' import makeModal %}

{% macro showMeta(bm) %}
    <table class="jbr-compact">
        <tbody>
            <tr>
                <th>URL</th>
                <td>{{ bm.url }} </td>
            </tr>
            {% if bm.note %}
                <tr>
                    <th>note</th>
                    <td>{{ bm.note }} </td>
                </tr>
            {% endif %}
            <tr>
                <th>visits</th>
                <td>{{ bm.visitCount }} </td>
            </tr>
            {% if bm.visitCount > 0 %}
                <tr>
                    <th>last visit</th>
                    <td>{{ bm.lastVisitStamp|formatStamp }} </td>
                </tr>
            {% endif %}
            <tr>
                <th>tags</th>
                <td class="jbr-tag-cloud" data-cloud-values="{{ bm.tags|tagListToStr }}"></td>
            </tr>
        </tbody>
    </table>
{% endmacro %}

{% macro showButtons(bm) %}
    <div>
        <a class="button is-small" href="{{ url_for('bookmark.edit', id=bm.id) }}">edit</a>
        {% set modalId = 'bm-modal-' ~ bm.id %}
        {% set delUrl = url_for('bookmark.delete', id=bm.id) %}
        <a class="button is-small jbr-modal" data-jbr-target="{{ modalId }}" href="#">delete</a>
        {{ makeModal(modalId, 'Really delete the bookmark?', 'Delete', delUrl) }}
    </div>
{% endmacro %}

{% block modHead %}
    <link rel="stylesheet" href="{{ url_for('bookmark.static', filename='css/style.css') }}">
{% endblock %}

{% block title %}Bookmarks Index{% endblock %}

{% block body %}

    <h1>Bookmarks Index</h1>

    <ol class="bm-list">
        {% for bm in bookmarks -%}
            <li>
                <a class="content is-large" href="{{ url_for('bookmark.visit', id=bm.id) }}">{{ bm.title }}</a>
                <i class="plus-minus fa fa-plus-square-o" data-toggle="bm-meta-{{ bm.id }}"></i>
                <div id="bm-meta-{{ bm.id }}" class="bm-meta">
                    {{ showMeta(bm) }}
                    {{ showButtons(bm) }}
                </div>
            </li>
        {%- endfor %}
    </ol>

{% endblock body %}

{% block sidebar %}
    {% include 'bookmark/_sidebar.html' %}
{% endblock %}

app/mods/bookmark/templates/bookmark/search.html
{% extends 'app/layout.html' %}
{% block title %}(Detailed) Search 4 Bookmark{% endblock %}

{% block body %}
    <h1>{{ self.title() }}</h1>

    <form action="{{ url_for('bookmark.search') }}" method="post">

        <div class="field">
            <label class="label" for="text">Text</label>
            <div class="control">
                <input type="text" class="form-control" id="q" name="q">
            </div>  
        </div>

        <div class="field is-grouped">
            <div class="control">
                <button class="button is-link" type="submit">Search</button>
            </div>
            <div class="control">
                <a class="button is-light" href="{{ url_for('bookmark.index') }}">Cancel</a>
            </div>
        </div>

    </form>
{% endblock %}